receivers:
  otlp:
    protocols:
      grpc: {}
  prometheus:
    config:
      scrape_configs:
        - job_name: 'rtsper'
          static_configs:
            - targets: ['host.docker.internal:8083','172.17.0.1:8083','127.0.0.1:8083']

exporters:
  prometheus:
    # Use a non-default port to avoid bind conflicts on hosts where 8888 is taken.
    endpoint: "0.0.0.0:8889"

service:
  pipelines:
    metrics:
      receivers: [otlp, prometheus]
      exporters: [prometheus]
