version: '3.8'

services:
  rtsper:
    image: "ghcr.io/${GHCR_OWNER}/${GHCR_REPO}:${COMMIT_SHA}"
    ports:
      - "9191:9191" # publisher port
      - "9192:9192" # subscriber port
      - "8080:8080" # admin /metrics
    command: ["-log-level=warn"]
    env_file:
      - .env
    networks:
      - rtsnet

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./rules.yml:/etc/prometheus/rules.yml:ro
    ports:
      - "9090:9090"
    networks:
      - rtsnet

  grafana:
    image: grafana/grafana:9.3.2
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_INSTALL_PLUGINS=marcusolsson-picture-panel,grafana-image-renderer
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ../grafana/dashboard.json:/var/lib/grafana/dashboards/rtsper-dashboard.json:ro
    networks:
      - rtsnet

  hls:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - ./hls:/usr/share/nginx/html/hls
    ports:
      - "8088:80"
    networks:
      - rtsnet

networks:
  rtsnet:
    driver: bridge

volumes:
  grafana-storage:
